name: Release

on:
  push:
    branches: [ main, alpha ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v -o ./mds-server

      - name: Test
        run: go test -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: mds-server
          # A file, directory or wildcard pattern that describes what to upload
          path: ./mds-server
          # The desired behavior if no files are found using the provided path.

  release:
    needs:
      - build
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm install @semantic-release/changelog @semantic-release/git @semantic-release/github
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}